### ISSUE TITLE
ngx-select2 not working with angular5

### ISSUE THREAD

**Issue by jjoao07** [lon-yang/ngx-select2#4]
Hi man!

I got a bug when I upgraded my project from angular 4.3 to angular 5
the issue is like below the screenshot

![image](https://user-images.githubusercontent.com/19816874/32611446-60b0460e-c56e-11e7-9664-475fa6d22283.png)

So I have looked around before I come posting here, and check what others are saying regarding the similar issue.

https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325

So can you please check it if you don't mind, maybe is there any workaround.

**Comment by lon-yang** [comment]
Got it

**Comment by jjoao07** [comment]
Hi @lon-yang 

Did you had time to check out on it,
or should I try to follow this discussion [Here](https://github.com/angular/angular-cli/issues/8284#issuecomment-343656917)

**Comment by lon-yang** [comment]
Can you try that?

**Comment by ctung** [comment]
I'm no expert, and I wasn't able to make the tsconfig.json edits work.

However I was able to get it working by copying the ngx-select2 module and the select2 component directly into my project, so the ts compiler is able to see them. So that's another workaround option, if you need to get it working right away.

But yes, the real fix seems to only include js in the npm module, instead of the ts.
